[package]
name = "lebanon"
version = "0.1.0"
edition = "2021"

[dependencies]
enclose = "1.1.8"
heck = "0.4.0"
hex = "0.4.3"
leb128 = "0.2.5"
log = "0.4.17"
tap = "1.0.1"
wasm-logger = "0.2.0"
web-sys = "0.3.60"
yew = { version = "0.20.0", features = ["csr"] }
